### ISSUE TITLE
Either allow automountServiceAccountToken or provide a flag

### ISSUE THREAD

**Issue by victorgetz** [gogatekeeper/helm-gogatekeeper#12]
It would be nice if you could provide a flag for automountServiceAccountToken inside the deployment.yaml.

Because Secret Injection Tools like https://github.com/SparebankenVest/azure-key-vault-to-kubernetes depend on it.

See also: https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/issues/265

Thanks !

**Comment by p53** [comment]
just fyi, are you aware of risks? https://hackersvanguard.com/abuse-kubernetes-with-the-automountserviceaccounttoken/

**Comment by p53** [comment]
@victorgetz added option

**Comment by tspearconquest** [comment]
Hi, I found this issue linked to https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/issues/265 and wanted to highlight a different fix which I've documented in https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/issues/424 and would be more secure. I realize this was closed, but highly recommend removing this feature in favor of the more secure solution.

**Comment by p53** [comment]
Will look at it

**Comment by p53** [comment]
@tspearconquest as i checked secure deployment (in cases automount is disabled) can be achieved by .Values.extraVolumeMounts, but anyway securing should be done on level of service account https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#opt-out-of-api-credential-automounting

**Comment by p53** [comment]
hmm ok thanks for info, maybe it would be good to add some note to helm docu that there is secure way to do it and later when people are used to more secure option maybe remove this option
