### ISSUE TITLE
Image tag label too long when used together with digest

### ISSUE THREAD

**Issue by stxm** [gogatekeeper/helm-gogatekeeper#46]
Hi
Using image tag together with image digest in values files makes the label too long to be accepted. 

https://github.com/gogatekeeper/helm-gogatekeeper/blob/e342c3f76f74604b6957fddeb2d6c55f694019c4/charts/gatekeeper/templates/_helpers.tpl#L40

> Helm install failed: 5 errors occurred: * ServiceAccount "gogatekeeper-dashboard" is invalid: [metadata.labels: Invalid value: "2.5.0@sha256:3746b95cc6d76276067deb741fefcc878c8c6ca8c90ea61fe3cc56db5b29a332": must be no more than 63 characters, metadata.labels: Invalid value: 
> "2.5.0@sha256:3746b95cc6d76276067deb741fefcc878c8c6ca8c90ea61fe3cc56db5b29a332": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]

**Comment by p53** [comment]
hi, thanks for creating issue, will look at it
